import os
import tarfile

from exceptions import ModelExtractionException

def write_named_pdbs( path, names, dirs, tarballs ):
	try:
		f = open( path, 'w' )
	except Exception as e:
		raise ModelExtractionException( "Failure opening output file: %s" % (e) )

	for (i,n) in enumerate(names):
		tmp, pdb = "%s.pdb" % n, None

		for d in dirs:
			path = os.path.join(d,tmp)

			if( os.access( path, os.R_OK ) ):
				if( pdb != None ):
					print "WARNING: duplicate named PDBs (\"%s\") detected!" % (n)
				else:
					try:
						pdb = open(path, 'r').read().strip()
					except Exception as e:
						raise ModelExtractionException( "Could not read PDB at \"%s\"" % (path) )

		for t in tarballs:
			if(  tmp in t.getnames() ):
				if( pdb != None ):
					print "WARNING: duplicate named PDBs (\"%s\") detected!" % (n)
				else:
					try:
						member = t.getmember(tmp)
						pdb = t.extractfile(member).read().strip()
					except Exception as e:
						raise ModelExtractionException( "Could not extract PDB \"%s\" from tarball \"%s\"" % (n,t.name) )

		if(pdb == None):
			raise ModelExtractionException( "Could not find pdb \"%s\" in any of the provided resources" % (n) )

		try:
			f.write("MODEL        %d\n%s\nENDMDL\n" % (i+1, pdb ) )
		except Exception as e:
			raise ModelExtractionException( "Could not append PDB to output: %s" % (e) )

	f.close()

def write_model_attributes( path, name, attributes ):
	f = open( path, 'w' )
	f.write("""# generated by make_generation_models
attribute: %s
match mode: 1-to-1
recipient: molecules
""" % name)
	for (i,a) in enumerate(attributes):
		f.write("\t#0.%i\t%.3f\n" % (i+1,a))
	f.close()