#!/usr/bin/perl

#
# saxs_fit_plot - uses gnuplot to make a figure containing experimental data and a MESMER fit
# Author: Elihu Ihms (c) 2012
#

use File::Basename;
use File::Spec;

#
# default options for settings
#

$terminal = 'aqua';
$plotargs = ();

#
# get any specified vars
#

if( $#ARGV == -1 )
{
	print "Usage: curv_fit_plot [-t/-term <terminal>] [-out/-o <file>] [-arg 'arg'] <MESMER_fit_file.fit>\n";
	exit;
}

while ( $argcounter <= $#ARGV )
{
	if ( $ARGV[ $argcounter ] eq "-term" || $ARGV[ $argcounter ] eq "-t" )
	{
		$terminal = $ARGV[ $argcounter +1 ];
		$argcounter++;
	}
	elsif ( $ARGV[ $argcounter ] eq "-out" || $ARGV[ $argcounter ] eq "-o" )
	{
		$output = $ARGV[ $argcounter +1 ];
		$argcounter++;
	}
	elsif ( $ARGV[ $argcounter ] eq "-inc" )
	{
		$wait = $ARGV[ $argcounter +1 ];
		$argcounter++;
	}
	elsif ( $ARGV[ $argcounter ] eq "-arg" )
	{
		push( @plotargs, $ARGV[ $argcounter +1 ] );
		$argcounter++;
	}
	else
	{
		$path = $ARGV[ $argcounter ];
		$path = File::Spec->rel2abs( $path );
		
		if( ! -f $path)
		{
			print "Bad option or fit file specified: \"$ARGV[ $argcounter ]\"\n";
			exit;
		}
	}
	$argcounter++;
}

#
# done with argument parsing
#

$title = basename( $path );
$title =~ s/\_/\\\_/g;

# open the pipe to GNUPLOT and make it hot
open( GNUPLOT, "| /usr/bin/gnuplot");
select GNUPLOT;
$| = 1;
select STDOUT;

print GNUPLOT <<EOPLOT;
	set terminal $terminal enhanced
EOPLOT
if( $output ne '' ){
	print GNUPLOT "set output \"$output\"\n";
}

print GNUPLOT <<EOPLOT;
reset
set encoding iso_8859_1
set title '$title'
set key left bottom

set multiplot

set size 1,1
set origin 0,0

set xlabel "Time (ns)"
set ylabel "Intensity (counts)"
#set logscale y
#set yrange [0.1 : 10000]

plot '$path' using 1:2 with points pt 6 lc rgb '#000000' title 'Experimental data', '$path' using 1:3 with lines lt -1 lc rgb '#FF0000' title 'MESMER fit'

set size 0.5,0.5
set origin 0.45,0.45

set title ' '
unset xlabel

unset logscale
set ylabel "I_{exp} - I_{fit}"
#set yrange [ 0.95 : 1.05 ]

plot '$file' using 1:(\$2-\$3) with points pt 6 lc rgb '#FF0000' notitle

EOPLOT

close( GNUPLOT );
